export let globalChildrenStore: any[] = [
  {
    id: "anak-1",
    nama: "Muhammad Arfan",
    nik: "3174011204220001",
    usiaBulan: 28,
    jenisKelamin: "L",
    namaOrangTua: "Siti Rahmawati",
    alamat: "RT 04 / RW 02 No. 12, Cilandak",
    beratBadan: 10.1,
    tinggiBadan: 78.5,
    zScoreBB_U: -2.35,
    zScoreTB_U: -3.10,
    zScoreBB_TB: -1.80,
    statusGizi: "Stunting",
    tanggalPemeriksaan: "2026-08-05",
    risikoLevel: "Kritis",
    rekomendasiAI: "[KRITIS] Indikasi Stunting Berat (-3.1 SD). Berisiko tinggi terhadap perkembangan kognitif. Segera rujuk ke Puskesmas & berikan PMT Pemulihan tinggi protein hewani (2 telur/hari).",
  },
  {
    id: "anak-2",
    nama: "Aisyah Putri Humaira",
    nik: "3174015509230002",
    usiaBulan: 14,
    jenisKelamin: "P",
    namaOrangTua: "Dewi Kurnia",
    alamat: "RT 02 / RW 02 No. 45, Kebayoran",
    beratBadan: 7.2,
    tinggiBadan: 71.0,
    zScoreBB_U: -2.45,
    zScoreTB_U: -1.60,
    zScoreBB_TB: -2.80,
    statusGizi: "Gizi Buruk",
    tanggalPemeriksaan: "2026-08-06",
    risikoLevel: "Kritis",
    rekomendasiAI: "[KRITIS] Indikasi Gizi Buruk Akut. Potensi komplikasi atropi otot & kekebalan tubuh. Berikan terapi nutrisi F-75/F-100 dan pantau penimbangan ketat tiap 3 hari.",
  },
  {
    id: "anak-3",
    nama: "Kenzo Rafasya",
    nik: "3174011801240003",
    usiaBulan: 31,
    jenisKelamin: "L",
    namaOrangTua: "Budi Santoso",
    alamat: "RT 01 / RW 03 No. 08, Pondok Labu",
    beratBadan: 11.4,
    tinggiBadan: 84.0,
    zScoreBB_U: -1.85,
    zScoreTB_U: -2.15,
    zScoreBB_TB: -1.10,
    statusGizi: "Stunting",
    tanggalPemeriksaan: "2026-08-04",
    risikoLevel: "Tinggi",
    rekomendasiAI: "[KRITIS] Stunting Sedang (-2.15 SD). Wajibkan konsumsi protein hewani harian (ikan, telur, hati ayam) dan pantau penimbangan bulanan.",
  },
  {
    id: "anak-4",
    nama: "Bilqis Anindya",
    nik: "3174016110220004",
    usiaBulan: 22,
    jenisKelamin: "P",
    namaOrangTua: "Rina Wijaya",
    alamat: "RT 05 / RW 01 No. 22, Gandaria",
    beratBadan: 9.2,
    tinggiBadan: 79.5,
    zScoreBB_U: -2.10,
    zScoreTB_U: -1.40,
    zScoreBB_TB: -2.05,
    statusGizi: "Gizi Kurang",
    tanggalPemeriksaan: "2026-08-06",
    risikoLevel: "Sedang",
    rekomendasiAI: "[PERINGATAN KLINIS] Indikasi Gizi Kurang. Berikan makanan tambahan (PMT) lokal kaya protein hewani dan suplemen zink.",
  },
  {
    id: "anak-5",
    nama: "Rayyan Azka Prasetya",
    nik: "3174010303210005",
    usiaBulan: 41,
    jenisKelamin: "L",
    namaOrangTua: "Hendra Prasetya",
    alamat: "RT 03 / RW 02 No. 19, Cipete",
    beratBadan: 15.2,
    tinggiBadan: 98.0,
    zScoreBB_U: 0.15,
    zScoreTB_U: 0.25,
    zScoreBB_TB: 0.10,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan anak sangat sesuai standar WHO. Pertahankan asupan nutrisi gizi seimbang.",
  },
  {
    id: "anak-6",
    nama: "Nabila Zhafira",
    nik: "3174014505230006",
    usiaBulan: 15,
    jenisKelamin: "P",
    namaOrangTua: "Anita Sari",
    alamat: "RT 02 / RW 01 No. 31, Cilandak",
    beratBadan: 9.5,
    tinggiBadan: 77.2,
    zScoreBB_U: 0.05,
    zScoreTB_U: 0.40,
    zScoreBB_TB: -0.20,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Kondisi gizi normal. Pertahankan asupan ASI dilanjutkan MPASI kaya zat besi.",
  },
  {
    id: "anak-7",
    nama: "Alvaro Maldini",
    nik: "3174011002230007",
    usiaBulan: 18,
    jenisKelamin: "L",
    namaOrangTua: "Rahmat Hidayat",
    alamat: "RT 06 / RW 04 No. 05, Jagakarsa",
    beratBadan: 10.8,
    tinggiBadan: 82.5,
    zScoreBB_U: 0.20,
    zScoreTB_U: 0.10,
    zScoreBB_TB: 0.15,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Tumbuh kembang balita sesuai kurva WHO. Pertahankan pola makan seimbang.",
  },
  {
    id: "anak-8",
    nama: "Clarissa Shanum",
    nik: "3174016511220008",
    usiaBulan: 21,
    jenisKelamin: "P",
    namaOrangTua: "Maya Saputri",
    alamat: "RT 01 / RW 05 No. 14, Pasar Minggu",
    beratBadan: 8.4,
    tinggiBadan: 74.0,
    zScoreBB_U: -2.30,
    zScoreTB_U: -3.05,
    zScoreBB_TB: -1.20,
    statusGizi: "Stunting",
    tanggalPemeriksaan: "2026-08-05",
    risikoLevel: "Kritis",
    rekomendasiAI: "[KRITIS] Indikasi Stunting Berat (-3.05 SD). Segera rujuk ke Puskesmas & berikan PMT Pemulihan tinggi protein hewani.",
  },
  {
    id: "anak-9",
    nama: "Davin Alfarizy",
    nik: "3174011406210009",
    usiaBulan: 38,
    jenisKelamin: "L",
    namaOrangTua: "Ferry Irawan",
    alamat: "RT 03 / RW 01 No. 42, Ragunan",
    beratBadan: 14.5,
    tinggiBadan: 96.0,
    zScoreBB_U: 0.10,
    zScoreTB_U: 0.20,
    zScoreBB_TB: 0.05,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-06",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan sangat optimal. Lanjutkan pengawasan rutin di posyandu.",
  },
  {
    id: "anak-10",
    nama: "Elshaddai Putri",
    nik: "3174015208220010",
    usiaBulan: 24,
    jenisKelamin: "P",
    namaOrangTua: "Grace Simanjuntak",
    alamat: "RT 04 / RW 03 No. 27, Lebak Bulus",
    beratBadan: 11.2,
    tinggiBadan: 86.0,
    zScoreBB_U: 0.00,
    zScoreTB_U: 0.30,
    zScoreBB_TB: -0.15,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Status gizi ideal WHO. Pertahankan pola asuh makanan kaya vitamin & mineral.",
  },
  {
    id: "anak-11",
    nama: "Fathan Mubina",
    nik: "3174010904240011",
    usiaBulan: 10,
    jenisKelamin: "L",
    namaOrangTua: "Ahmad Fauzi",
    alamat: "RT 02 / RW 06 No. 11, Lenteng Agung",
    beratBadan: 6.1,
    tinggiBadan: 66.5,
    zScoreBB_U: -2.60,
    zScoreTB_U: -2.10,
    zScoreBB_TB: -2.85,
    statusGizi: "Gizi Buruk",
    tanggalPemeriksaan: "2026-08-06",
    risikoLevel: "Kritis",
    rekomendasiAI: "[KRITIS] Indikasi Gizi Buruk Akut (BB/TB -2.85 SD). Wajib rujukan medis ke Poli Anak Puskesmas & suplementasi F-75.",
  },
  {
    id: "anak-12",
    nama: "Ghina Salsabila",
    nik: "3174014812230012",
    usiaBulan: 16,
    jenisKelamin: "P",
    namaOrangTua: "Nurul Hidayah",
    alamat: "RT 05 / RW 02 No. 09, Srengseng Sawah",
    beratBadan: 9.8,
    tinggiBadan: 78.0,
    zScoreBB_U: 0.05,
    zScoreTB_U: 0.10,
    zScoreBB_TB: 0.00,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Kondisi fisik balita sehat dan proporsional.",
  },
  {
    id: "anak-13",
    nama: "Hafizh Rizky",
    nik: "3174012101220013",
    usiaBulan: 30,
    jenisKelamin: "L",
    namaOrangTua: "Taufik Hidayat",
    alamat: "RT 03 / RW 04 No. 33, Tanjung Barat",
    beratBadan: 12.8,
    tinggiBadan: 90.0,
    zScoreBB_U: -0.10,
    zScoreTB_U: 0.00,
    zScoreBB_TB: -0.10,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-06",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan normal. Lanjutkan asupan protein hewani rutin.",
  },
  {
    id: "anak-14",
    nama: "Inara Kalila",
    nik: "3174015903230014",
    usiaBulan: 17,
    jenisKelamin: "P",
    namaOrangTua: "Dian Permata",
    alamat: "RT 07 / RW 01 No. 17, Pejaten",
    beratBadan: 7.9,
    tinggiBadan: 73.5,
    zScoreBB_U: -2.15,
    zScoreTB_U: -2.50,
    zScoreBB_TB: -1.30,
    statusGizi: "Stunting",
    tanggalPemeriksaan: "2026-08-05",
    risikoLevel: "Tinggi",
    rekomendasiAI: "[KRITIS] Indikasi Stunting Sedang (-2.5 SD). Rujuk konseling gizi dan tingkatkan asupan PMT lokal.",
  },
  {
    id: "anak-15",
    nama: "Januar Zidan",
    nik: "3174010101210015",
    usiaBulan: 43,
    jenisKelamin: "L",
    namaOrangTua: "Zulkifli",
    alamat: "RT 02 / RW 03 No. 51, Jati Padang",
    beratBadan: 16.0,
    tinggiBadan: 100.5,
    zScoreBB_U: 0.30,
    zScoreTB_U: 0.45,
    zScoreBB_TB: 0.10,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan sangat baik. Pertahankan pola makan seimbang.",
  },
  {
    id: "anak-16",
    nama: "Kayla Nadhira",
    nik: "3174016707220016",
    usiaBulan: 25,
    jenisKelamin: "P",
    namaOrangTua: "Fitriani",
    alamat: "RT 04 / RW 05 No. 04, Kebagusan",
    beratBadan: 9.6,
    tinggiBadan: 81.0,
    zScoreBB_U: -1.95,
    zScoreTB_U: -2.35,
    zScoreBB_TB: -1.15,
    statusGizi: "Stunting",
    tanggalPemeriksaan: "2026-08-05",
    risikoLevel: "Tinggi",
    rekomendasiAI: "[KRITIS] Stunting Sedang (TB/U -2.35 SD). Berikan konseling pola asuh nutrisi & PMT protein hewani.",
  },
  {
    id: "anak-17",
    nama: "Lionel Nathan",
    nik: "3174011505230017",
    usiaBulan: 15,
    jenisKelamin: "L",
    namaOrangTua: "Stefanus",
    alamat: "RT 01 / RW 02 No. 88, Ciganjur",
    beratBadan: 10.2,
    tinggiBadan: 79.0,
    zScoreBB_U: 0.10,
    zScoreTB_U: 0.20,
    zScoreBB_TB: 0.00,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan fisik balita optimal sesuai WHO.",
  },
  {
    id: "anak-18",
    nama: "Mikayla Mikha",
    nik: "3174014202240018",
    usiaBulan: 12,
    jenisKelamin: "P",
    namaOrangTua: "Kartika Sari",
    alamat: "RT 06 / RW 01 No. 29, Jagakarsa",
    beratBadan: 8.9,
    tinggiBadan: 74.5,
    zScoreBB_U: 0.00,
    zScoreTB_U: 0.10,
    zScoreBB_TB: -0.10,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan normal. Lanjutkan penimbangan rutin tiap bulan.",
  },
  {
    id: "anak-19",
    nama: "Naufal Abshar",
    nik: "3174012509210019",
    usiaBulan: 35,
    jenisKelamin: "L",
    namaOrangTua: "Irwan Syah",
    alamat: "RT 03 / RW 05 No. 16, Pondok Labu",
    beratBadan: 13.8,
    tinggiBadan: 94.0,
    zScoreBB_U: 0.05,
    zScoreTB_U: 0.15,
    zScoreBB_TB: -0.05,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Status gizi ideal WHO. Pertahankan pola asuh seimbang.",
  },
  {
    id: "anak-20",
    nama: "Olivia Naura",
    nik: "3174015111230020",
    usiaBulan: 13,
    jenisKelamin: "P",
    namaOrangTua: "Widya Astuti",
    alamat: "RT 02 / RW 04 No. 37, Cipete",
    beratBadan: 7.0,
    tinggiBadan: 69.5,
    zScoreBB_U: -2.70,
    zScoreTB_U: -2.85,
    zScoreBB_TB: -2.15,
    statusGizi: "Gizi Kurang",
    tanggalPemeriksaan: "2026-08-06",
    risikoLevel: "Sedang",
    rekomendasiAI: "[PERINGATAN KLINIS] Indikasi Gizi Kurang kronis. Berikan suplemen zink & PMT lokal tinggi energi.",
  },
  {
    id: "anak-21",
    nama: "Pradipta Arya",
    nik: "3174010808220021",
    usiaBulan: 24,
    jenisKelamin: "L",
    namaOrangTua: "Agus Setiawan",
    alamat: "RT 05 / RW 03 No. 40, Gandaria",
    beratBadan: 11.8,
    tinggiBadan: 87.5,
    zScoreBB_U: 0.25,
    zScoreTB_U: 0.50,
    zScoreBB_TB: -0.10,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan sangat proporsional.",
  },
  {
    id: "anak-22",
    nama: "Qonita Hanania",
    nik: "3174016304230022",
    usiaBulan: 16,
    jenisKelamin: "P",
    namaOrangTua: "Zahra Amalia",
    alamat: "RT 01 / RW 02 No. 62, Cilandak",
    beratBadan: 9.6,
    tinggiBadan: 77.5,
    zScoreBB_U: 0.00,
    zScoreTB_U: 0.05,
    zScoreBB_TB: -0.05,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Kondisi gizi normal.",
  },
  {
    id: "anak-23",
    nama: "Raffa Ahmad",
    nik: "3174011910210023",
    usiaBulan: 34,
    jenisKelamin: "L",
    namaOrangTua: "Rifky Firdaus",
    alamat: "RT 04 / RW 01 No. 23, Kebayoran",
    beratBadan: 13.5,
    tinggiBadan: 93.0,
    zScoreBB_U: 0.00,
    zScoreTB_U: 0.10,
    zScoreBB_TB: -0.10,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Tumbuh kembang ideal sesuai WHO.",
  },
  {
    id: "anak-24",
    nama: "Siti Humaira",
    nik: "3174014909220024",
    usiaBulan: 23,
    jenisKelamin: "P",
    namaOrangTua: "Halimah",
    alamat: "RT 03 / RW 06 No. 18, Ragunan",
    beratBadan: 7.8,
    tinggiBadan: 75.0,
    zScoreBB_U: -2.80,
    zScoreTB_U: -3.20,
    zScoreBB_TB: -1.90,
    statusGizi: "Stunting",
    tanggalPemeriksaan: "2026-08-05",
    risikoLevel: "Kritis",
    rekomendasiAI: "[KRITIS] Indikasi Stunting Berat (-3.2 SD). Segera rujuk ke Puskesmas & berikan PMT Pemulihan protein hewani.",
  },
  {
    id: "anak-25",
    nama: "Tristan Pratama",
    nik: "3174010707230025",
    usiaBulan: 13,
    jenisKelamin: "L",
    namaOrangTua: "Bambang Pamungkas",
    alamat: "RT 02 / RW 05 No. 30, Lebak Bulus",
    beratBadan: 9.7,
    tinggiBadan: 76.0,
    zScoreBB_U: 0.10,
    zScoreTB_U: 0.15,
    zScoreBB_TB: 0.00,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan normal dan sehat.",
  },
  {
    id: "anak-26",
    nama: "Ulya Syarifah",
    nik: "3174015606210026",
    usiaBulan: 38,
    jenisKelamin: "P",
    namaOrangTua: "Syarifuddin",
    alamat: "RT 05 / RW 04 No. 44, Lenteng Agung",
    beratBadan: 14.8,
    tinggiBadan: 97.0,
    zScoreBB_U: 0.20,
    zScoreTB_U: 0.30,
    zScoreBB_TB: -0.05,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Status gizi normal ideal.",
  },
  {
    id: "anak-27",
    nama: "Vino Bastian",
    nik: "3174011111220027",
    usiaBulan: 21,
    jenisKelamin: "L",
    namaOrangTua: "Bambang Tri",
    alamat: "RT 01 / RW 01 No. 71, Srengseng",
    beratBadan: 10.9,
    tinggiBadan: 83.5,
    zScoreBB_U: 0.00,
    zScoreTB_U: 0.20,
    zScoreBB_TB: -0.15,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan proporsional.",
  },
  {
    id: "anak-28",
    nama: "Wania Azahra",
    nik: "3174014303240028",
    usiaBulan: 11,
    jenisKelamin: "P",
    namaOrangTua: "Wawan Kurniawan",
    alamat: "RT 03 / RW 02 No. 25, Pejaten",
    beratBadan: 6.0,
    tinggiBadan: 67.0,
    zScoreBB_U: -2.75,
    zScoreTB_U: -2.30,
    zScoreBB_TB: -2.95,
    statusGizi: "Gizi Buruk",
    tanggalPemeriksaan: "2026-08-06",
    risikoLevel: "Kritis",
    rekomendasiAI: "[KRITIS] Indikasi Gizi Buruk Akut. Segera konsultasikan ke Dokter Spesialis Anak Puskesmas.",
  },
  {
    id: "anak-29",
    nama: "Xavier Gibran",
    nik: "3174012705220029",
    usiaBulan: 27,
    jenisKelamin: "L",
    namaOrangTua: "David Wibowo",
    alamat: "RT 06 / RW 03 No. 12, Jati Padang",
    beratBadan: 12.2,
    tinggiBadan: 88.0,
    zScoreBB_U: 0.15,
    zScoreTB_U: 0.20,
    zScoreBB_TB: 0.00,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Tumbuh kembang optimal.",
  },
  {
    id: "anak-30",
    nama: "Yasmin Aliyya",
    nik: "3174016010210030",
    usiaBulan: 34,
    jenisKelamin: "P",
    namaOrangTua: "Yusuf Mansur",
    alamat: "RT 02 / RW 05 No. 55, Kebagusan",
    beratBadan: 13.2,
    tinggiBadan: 92.5,
    zScoreBB_U: -0.05,
    zScoreTB_U: 0.00,
    zScoreBB_TB: -0.05,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan fisik normal.",
  },
  {
    id: "anak-31",
    nama: "Zayn Malik",
    nik: "3174011301230031",
    usiaBulan: 19,
    jenisKelamin: "L",
    namaOrangTua: "Zulham Efendi",
    alamat: "RT 04 / RW 04 No. 03, Ciganjur",
    beratBadan: 10.6,
    tinggiBadan: 81.5,
    zScoreBB_U: 0.10,
    zScoreTB_U: 0.20,
    zScoreBB_TB: -0.05,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Status gizi ideal.",
  },
  {
    id: "anak-32",
    nama: "Anindya Keisha",
    nik: "3174015808230032",
    usiaBulan: 12,
    jenisKelamin: "P",
    namaOrangTua: "Andi Wijaya",
    alamat: "RT 01 / RW 06 No. 27, Tanjung Barat",
    beratBadan: 8.8,
    tinggiBadan: 74.0,
    zScoreBB_U: 0.00,
    zScoreTB_U: 0.05,
    zScoreBB_TB: -0.05,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan normal.",
  },
  {
    id: "anak-33",
    nama: "Bagas Kara",
    nik: "3174010203220033",
    usiaBulan: 29,
    jenisKelamin: "L",
    namaOrangTua: "Baskoro",
    alamat: "RT 03 / RW 01 No. 49, Pondok Labu",
    beratBadan: 9.8,
    tinggiBadan: 81.0,
    zScoreBB_U: -2.20,
    zScoreTB_U: -2.40,
    zScoreBB_TB: -1.15,
    statusGizi: "Stunting",
    tanggalPemeriksaan: "2026-08-05",
    risikoLevel: "Tinggi",
    rekomendasiAI: "[KRITIS] Indikasi Stunting Sedang (-2.4 SD). Rujuk konseling gizi dan tingkatkan konsumsi protein hewani.",
  },
  {
    id: "anak-34",
    nama: "Chintya Laura",
    nik: "3174016404210034",
    usiaBulan: 40,
    jenisKelamin: "P",
    namaOrangTua: "Candra Gunawan",
    alamat: "RT 05 / RW 02 No. 15, Cipete",
    beratBadan: 15.0,
    tinggiBadan: 97.5,
    zScoreBB_U: 0.10,
    zScoreTB_U: 0.20,
    zScoreBB_TB: -0.05,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Pertumbuhan fisik sangat baik.",
  },
  {
    id: "anak-35",
    nama: "Dzaky Asyraf",
    nik: "3174011606230035",
    usiaBulan: 14,
    jenisKelamin: "L",
    namaOrangTua: "Deri Kurniawan",
    alamat: "RT 02 / RW 03 No. 38, Gandaria",
    beratBadan: 7.4,
    tinggiBadan: 71.5,
    zScoreBB_U: -2.25,
    zScoreTB_U: -1.70,
    zScoreBB_TB: -2.30,
    statusGizi: "Gizi Kurang",
    tanggalPemeriksaan: "2026-08-06",
    risikoLevel: "Sedang",
    rekomendasiAI: "[PERINGATAN KLINIS] Indikasi Gizi Kurang. Berikan Makanan Tambahan (PMT) lokal berbasis telur dan tempe.",
  },
  {
    id: "anak-36",
    nama: "Evelyn Gracia",
    nik: "3174015010220036",
    usiaBulan: 22,
    jenisKelamin: "P",
    namaOrangTua: "Edward",
    alamat: "RT 04 / RW 01 No. 06, Kebayoran",
    beratBadan: 10.8,
    tinggiBadan: 84.5,
    zScoreBB_U: 0.15,
    zScoreTB_U: 0.30,
    zScoreBB_TB: -0.10,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "[EVALUASI OPTIMAL] Kondisi gizi normal ideal.",
  },
];

export function removeChildFromStore(id: string) {
  globalChildrenStore = globalChildrenStore.filter((c) => c.id !== id && c.nik !== id);
}

export function prependChildToStore(child: any) {
  globalChildrenStore.unshift(child);
}

export function getDynamicSummary() {
  const totalAnak = globalChildrenStore.length;
  const anakBerisiko = globalChildrenStore.filter(
    (c) => c.statusGizi && c.statusGizi !== "Normal"
  ).length;
  const anakNormal = totalAnak - anakBerisiko;
  const persentaseNormal = totalAnak > 0 ? parseFloat(((anakNormal / totalAnak) * 100).toFixed(1)) : 100;
  const pemeriksaanBulanIni = totalAnak;

  return {
    totalAnak,
    anakBerisiko,
    pemeriksaanBulanIni,
    persentaseNormal,
  };
}

export function getChartData() {
  const normal = globalChildrenStore.filter((c) => c.statusGizi === "Normal").length;
  const giziKurang = globalChildrenStore.filter((c) => c.statusGizi === "Gizi Kurang").length;
  const giziBuruk = globalChildrenStore.filter((c) => c.statusGizi === "Gizi Buruk").length;
  const stunting = globalChildrenStore.filter((c) => c.statusGizi === "Stunting").length;

  return [
    { kategori: "Normal", jumlah: normal, fill: "#10b981" },
    { kategori: "Gizi Kurang", jumlah: giziKurang, fill: "#f59e0b" },
    { kategori: "Gizi Buruk", jumlah: giziBuruk, fill: "#ef4444" },
    { kategori: "Stunting", jumlah: stunting, fill: "#e11d48" },
  ];
}
