export let globalChildrenStore: any[] = [
  {
    id: "anak-1",
    nama: "Muhammad Arfan",
    nik: "3174011204220001",
    usiaBulan: 28,
    jenisKelamin: "L",
    namaOrangTua: "Siti Rahmawati",
    alamat: "RT 04 / RW 02 No. 12",
    beratBadan: 10.1,
    tinggiBadan: 78.5,
    zScoreBB_U: -2.35,
    zScoreTB_U: -3.10,
    zScoreBB_TB: -1.80,
    statusGizi: "Stunting",
    tanggalPemeriksaan: "2026-08-05",
    risikoLevel: "Kritis",
    rekomendasiAI: "Indikasi Stunting Berat (TB/U < -3 SD). Segera rujuk ke Puskesmas Cilandak untuk intervensi PMT Pemulihan tinggi protein.",
  },
  {
    id: "anak-2",
    nama: "Aisyah Putri Humaira",
    nik: "3174015509230002",
    usiaBulan: 14,
    jenisKelamin: "P",
    namaOrangTua: "Dewi Kurnia",
    alamat: "RT 02 / RW 02 No. 45",
    beratBadan: 7.2,
    tinggiBadan: 71.0,
    zScoreBB_U: -2.45,
    zScoreTB_U: -1.60,
    zScoreBB_TB: -2.80,
    statusGizi: "Gizi Buruk",
    tanggalPemeriksaan: "2026-08-06",
    risikoLevel: "Kritis",
    rekomendasiAI: "Z-score BB/TB < -3 SD mengindikasikan Gizi Buruk. Berikan konseling ASI Eksklusif/MPASI padat gizi.",
  },
  {
    id: "anak-3",
    nama: "Kenzo Rafasya",
    nik: "3174011801240003",
    usiaBulan: 31,
    jenisKelamin: "L",
    namaOrangTua: "Budi Santoso",
    alamat: "RT 01 / RW 03 No. 08",
    beratBadan: 11.4,
    tinggiBadan: 84.0,
    zScoreBB_U: -1.85,
    zScoreTB_U: -2.15,
    zScoreBB_TB: -1.10,
    statusGizi: "Stunting",
    tanggalPemeriksaan: "2026-08-04",
    risikoLevel: "Tinggi",
    rekomendasiAI: "Kategori Stunting Sedang (TB/U -2 s/d -3 SD). Edukasi pola asuh nutrisi kaya protein hewani.",
  },
  {
    id: "anak-4",
    nama: "Bilqis Anindya",
    nik: "3174016110220004",
    usiaBulan: 22,
    jenisKelamin: "P",
    namaOrangTua: "Rina Wijaya",
    alamat: "RT 05 / RW 01 No. 22",
    beratBadan: 9.2,
    tinggiBadan: 79.5,
    zScoreBB_U: -2.10,
    zScoreTB_U: -1.40,
    zScoreBB_TB: -2.05,
    statusGizi: "Gizi Kurang",
    tanggalPemeriksaan: "2026-08-06",
    risikoLevel: "Sedang",
    rekomendasiAI: "BB/U & BB/TB menunjukkan Gizi Kurang. Berikan makanan tambahan (PMT) lokal berbasis tempe dan telur.",
  },
  {
    id: "anak-5",
    nama: "Rayyan Azka Prasetya",
    nik: "3174010303210005",
    usiaBulan: 41,
    jenisKelamin: "L",
    namaOrangTua: "Hendra Prasetya",
    alamat: "RT 03 / RW 02 No. 19",
    beratBadan: 15.2,
    tinggiBadan: 98.0,
    zScoreBB_U: 0.15,
    zScoreTB_U: 0.25,
    zScoreBB_TB: 0.10,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "Pertumbuhan anak sangat optimal sesuai standar WHO. Pertahankan pola makan seimbang.",
  },
  {
    id: "anak-6",
    nama: "Nabila Zhafira",
    nik: "3174014505230006",
    usiaBulan: 15,
    jenisKelamin: "P",
    namaOrangTua: "Anita Sari",
    alamat: "RT 02 / RW 01 No. 31",
    beratBadan: 9.5,
    tinggiBadan: 77.2,
    zScoreBB_U: 0.05,
    zScoreTB_U: 0.40,
    zScoreBB_TB: -0.20,
    statusGizi: "Normal",
    tanggalPemeriksaan: "2026-08-07",
    risikoLevel: "Rendah",
    rekomendasiAI: "Kondisi gizi normal. Pertahankan asupan ASI dilanjutkan MPASI kaya gizi.",
  },
];

export function removeChildFromStore(id: string) {
  globalChildrenStore = globalChildrenStore.filter((c) => c.id !== id && c.nik !== id);
}

export function prependChildToStore(child: any) {
  globalChildrenStore.unshift(child);
}
